### ISSUE TITLE
Missing data from signals_table and signals_metadata

### ISSUE THREAD

**Issue by flaviendaussy** [microsoft/adx-automotive-demos#25]
While working on an use case, Mario and we realised that the following data was missing:
- Missing group_name and source_can from signals_table
- Missing source_can from signals_metadata.

**Comment by msmarioo** [comment]
This is an important limitation as there are two types of time analysis that are common:
- by signal
- by frame

Missing the group_name means that it is not possible to group by frames when doing an analysis.

The same frames might be available in multiple CAN busses - eg. body/chassis or powertrain but the timestamps will be subtly different, so when making time analysis mixing the CAN busses can lead to icorrect results.

Proposed solution:
- add the group name and source_can to signals
- add the source_can also to signals_metadata
