### ISSUE TITLE
Detect Datatype within Asammdf and set to decimal for Datatypes not handled by Kusto

### ISSUE THREAD

**Issue by flaviendaussy** [microsoft/adx-automotive-demos#41]
In the testing phase, it was detected that uint64 signals were ingested as double64, which resulted in data losses.
The dtype of each signal needs to be used in order to choose which datatype to use in Kusto.
The datatypes we get from Asammdf should also be used as metadata in signals-metadata

**Comment by msmarioo** [comment]
Problem is very noticeable in uint64 datatypes, as they will lose precision when cast to a double.
We require a better handling of the different datatypes to avoid precision loss
