### ISSUE TITLE
Metadata file enhancements (.metadata.json)

### ISSUE THREAD

**Issue by sa1sen** [microsoft/adx-automotive-demos#66]
The metadata file (.metadata.json) lists out ALL the signals in the raw input file. As this file is used to generate the BRONZE_ASAMMDF_SIGNALS_METADATA table, we will also get the corrupted signals inside the signals column (datatype: dynamic). 

Ideally, we only want to successful signals to be captured in .metadata.json. Today, it looks like there is no link between metadata.json file and the decoding process overall (e.g. report.json file). 

@flaviendaussy

**Comment by msmarioo** [comment]
This was solved together with #67, now the signals metadata contains the status of the decoding. Expanding the bronze into silver allows to easily filter only the good signals (using a where clause)
