### ISSUE TITLE
Add signal-specific parsing sucess boolean + signal-specific records count within sinal metadata

### ISSUE THREAD

**Issue by flaviendaussy** [microsoft/adx-automotive-demos#67]
Within MetadataTools, need to add during the creation of metadata["signals"] a boolean field "signal_decoding_status" as well as a "records_count" field

**Comment by msmarioo** [comment]
Currently, the generated signals-metadata.json file does not contain information about the result of the decoding. This request is about delaying writing the information until this information is collected.
