### ISSUE TITLE
Decoding of Some String signals containing special characters fails

### ISSUE THREAD

**Issue by flaviendaussy** [microsoft/adx-automotive-demos#71]
Some string special characters can't be parsed correctly (example: degree symbol °) due to casting the arrays astype(str) in DecodeUtils.

Proposition is to replace in extractSignalsByType:
                stringSignals = decodedSignal.samples.astype(str)
by:
                stringSignals = decodedSignal.samples.astype("S32")

**Comment by msmarioo** [comment]
Fix was verified and accepted with the commit
